ALTER TABLE users
 ADD COLUMN must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
 ADD COLUMN foto_path VARCHAR(700) NULL,
 ADD COLUMN activo BOOLEAN NOT NULL DEFAULT TRUE,
 ADD COLUMN token_version BIGINT NOT NULL DEFAULT 0;
