/** Fuente reproducible para el diagrama Archify de las tres fases. */
const fs=require('fs');
const components=[
 ['pantallas','frontend','Tu espacio (Vue)','Menú · Inicio por rol · pantallas',40,150],
 ['facade','frontend','Mensajero (Facade)','auth · ClienteFacade · UsuarioFacade',350,150],
 ['nginx','cloud','Entrada (nginx)','Build Vue · /api → backend:8081',660,150],
 ['seguridad','backend','Acceso (JWT / RBAC)','Activo · versión · primer acceso',970,150],
 ['controller','backend','Recepción (Controller)','Auth · Clientes · Usuarios · Perfil',970,400],
 ['service','backend','Reglas (Service)','Validar · BCrypt · revocar · guardar',660,400],
 ['repository','backend','Archivo (Repository)','Interfaces Spring Data JPA',350,400],
 ['mysql','database','Datos (MySQL)','Usuarios · clientes · sesiones',40,400],
 ['flyway','database','Cambios (Flyway)','V1 → V2 → V3 al arrancar',40,650],
 ['futuro','external','Siguiente (modelo)','Empresa · taller · cliente_taller',350,650],
 ['photo','cloud','Fotos (disco privado)','UUID · JPG / PNG / WEBP · 15 MB',660,650],
];
const edge=(id,from,to,label,fromSide,toSide)=>({id,from,to,label,fromSide,toSide,...({dos:{labelAt:[625,125]},cuatro:{labelAt:[1130,330]},nueve:{labelAt:[820,580]},ocho:{labelAt:[200,580]}}[id]||{})});
const cards=[
 {dot:'violet',title:'Cómo leer este diagrama',items:['1. Empieza en Tu espacio y sigue las flechas numeradas del 1 al 9.','2. Cada color identifica una capa; las flechas muestran a quién pide ayuda.','3. Lee debajo los recorridos y permisos; Futuro todavía no tiene pantallas ni API.']},
 {dot:'cyan',title:'Glosario breve',items:['API: puerta que recibe solicitudes de las pantallas. JWT: comprobante de sesión firmado y de duración corta.','RBAC: permisos según el rol. Proxy: intermediario que dirige /api al backend.','Migración: cambio versionado de tablas. Repositorio: interfaz para leer y guardar datos.','Facade: servicio que simplifica las llamadas de una vista. BCrypt: hash usado para verificar contraseñas. Refresh: cookie que renueva la sesión.']},
 {dot:'violet',title:'Flujo de registro de cliente',items:['Recepción o Administración abre Registrar cliente desde el menú o Inicio.','Captura datos personales, contacto y dirección; añade una foto opcional al final y confirma.','ClienteFacade.create envía multipart y JWT; nginx admite hasta 16 MB por solicitud.','ClienteController → ClienteService valida mayoría de edad, formatos, duplicados y foto; Repository persiste en MySQL.','El archivo usa UUID bajo CLIENTES_PHOTO_DIR. La API devuelve 201, 400, 409 o 413 según el resultado.']},
 {dot:'cyan',title:'Capas y comunicación',items:['Vue usa AppShell para pantallas internas y conserva el acceso dividido; primer acceso no muestra menú.','Las vistas llaman servicios/Facade, que agregan JWT y renuevan la cookie HttpOnly de forma silenciosa.','nginx.conf sirve frontend/dist en 8088 y dirige /api a host.docker.internal:8081; límite 16 MB y cabeceras básicas.','JwtFilter consulta el usuario: bloquea inactivos, versiones revocadas y acciones ajenas al primer acceso.','Controller → Service → Repository. Solo el servicio accede a persistencia para las operaciones nuevas.','MySQL guarda rutas de fotos; los bytes permanecen en disco y se descargan por endpoints protegidos.']},
 {dot:'violet',title:'Menú, Inicio y clientes',items:['Menú: iconos en 76 px; hamburguesa/hover despliegan 250 px; drawer en móvil. Configuración y Salir están al fondo.','Inicio muestra perfil, fecha, correo, rol y cantidad real de tarjetas; sin lista de clientes ni cifras inventadas.','Clientes busca q por nombre, teléfono o correo, pagina cinco filas y abre detalle/foto en panel lateral.','403 y 404 permanecen dentro de AppShell; un refresh fallido avisa que la sesión expiró.']},
 {dot:'cyan',title:'Alta, baja y restablecimiento de usuarios',items:['Solo Administración consulta /api/usuarios y abre Dar de alta usuario; los cinco roles aparecen dentro del panel.','Crear guarda BCrypt y must_change_password=true; correo repetido responde 409.','Desactivar impide entrar y revoca access/refresh. No se permite baja propia ni del último administrador activo.','Restablecer genera una temporal válida aleatoria, la devuelve una vez y revoca sesiones previas.','La baja es lógica (activo=false); no elimina la cuenta ni sus datos históricos.']},
 {dot:'cyan',title:'Primer acceso y configuración',items:['Login/refresh devuelven mustChangePassword; mientras sea true el servidor solo admite change-password, logout y refresh.','El guard redirige a /cambiar-contrasena: temporal, nueva y confirmación; al éxito recibe tokens nuevos y abre Inicio.','Configuración permite cambiar o quitar la foto propia; se refleja en la barra superior y en Inicio.','Claro/Oscuro se guarda en localStorage y se aplica antes de renderizar todas las vistas.','Cambiar contraseña abre modal: valida la actual, política, confirmación y que sea distinta; revoca sesiones previas.']},
 {dot:'cyan',title:'Qué puede hacer cada rol',items:['ADMINISTRADOR: crear/consultar clientes; crear/consultar/activar/desactivar usuarios; restablecer contraseñas; consultar roles.','RECEPCIONISTA: crear y consultar clientes. GERENTE: consultar clientes, detalle y fotos.','MECANICO y AYUDANTE: Inicio sin accesos operativos asignados.','Todos: Configuración, foto propia, cambio de contraseña y salir; el primer acceso restringe temporalmente todo lo demás.','Editar permisos dinámicos es futuro; hoy los permisos operativos están definidos y validados en servidor.']},
 {dot:'amber',title:'Futuro',items:['Empresa, taller, cliente.empresa_id y cliente_taller existen como estructura, sin API de asociación.','Pendientes: permisos editables, caducidad de temporales, editar/dar de baja clientes y bitácora visible.','También pendientes: aviso de privacidad, correo transaccional, HTTPS de producción y suite automatizada integrada en CI.']},
 {dot:'violet',title:'Índice de nodos',items:components.map(([id,type,label,sub])=>`${label}: ${sub}. Identificador: ${id}.`)},
];
const source={schema_version:1,diagram_type:'architecture',meta:{title:'taller uno — cómo funciona',subtitle:'Personas, pantallas y datos · Estado real de las fases 1, 2 y 3',output:'taller-mecanico.html',quality_profile:'standard',visual_preset:'editorial',animation:'none',legend:{mode:'all',entries:{frontend:{label:'Pantallas y servicios · lavanda'},backend:{label:'Reglas y seguridad · azul'},database:{label:'Datos y migraciones · verde'},cloud:{label:'Entrada y archivos · durazno'},external:{label:'Modelo futuro · amarillo'}}}},components:components.map(([id,type,label,sublabel,x,y])=>({id,type,label,sublabel,pos:[x,y],size:[240,110]})),boundaries:[],connections:[edge('uno','pantallas','facade','1 · solicita','right','left'),edge('dos','facade','nginx','2 · envía /api','right','left'),edge('tres','nginx','seguridad','3 · verifica','right','left'),edge('cuatro','seguridad','controller','4 · autoriza','bottom','top'),edge('cinco','controller','service','5 · valida','left','right'),edge('seis','service','repository','6 · persiste','left','right'),edge('siete','repository','mysql','7 · SQL','left','right'),edge('ocho','flyway','mysql','8 · migra','top','bottom'),edge('nueve','service','photo','9 · guarda foto','bottom','top')],cards};
fs.writeFileSync('docs/arquitectura/taller-mecanico.architecture.json',JSON.stringify(source,null,2)+'\n');
