<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue'
import Swal from 'sweetalert2'
import {UsuarioFacade,type Usuario} from '../services/UsuarioFacade'
const rows=ref<Usuario[]>([]),page=ref(0),pages=ref(0),total=ref(0),loading=ref(false),error=ref(''),panel=ref(false),busy=ref(false),roles=ref<Array<{name:string;description:string}>>([])
const form=reactive({fullName:'',email:'',password:'',role:'RECEPCIONISTA'})
const labels:Record<string,string>={ADMINISTRADOR:'Administrador',GERENTE:'Gerente',RECEPCIONISTA:'Recepcionista',MECANICO:'Mecánico',AYUDANTE:'Ayudante'}
/** Carga página administrativa con estados de carga y error. */
async function load(){loading.value=true;error.value='';try{const result=await UsuarioFacade.list(page.value);rows.value=result.content;total.value=result.totalElements;pages.value=result.totalPages}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
/** Consulta roles únicamente al abrir el alta. */
async function open(){try{roles.value=await UsuarioFacade.roles();panel.value=true}catch(e){await fail(e)}}
/** Presenta errores sin datos internos. */
async function fail(e:unknown){await Swal.fire({icon:'error',title:'No se pudo completar',text:(e as Error).message})}
/** Confirma y crea una cuenta con temporal. */
async function create(){if(!(await Swal.fire({title:'¿Crear usuario?',text:form.fullName,icon:'question',showCancelButton:true,confirmButtonText:'Crear',cancelButtonText:'Cancelar'})).isConfirmed)return;busy.value=true;try{await UsuarioFacade.create({...form});panel.value=false;Object.assign(form,{fullName:'',email:'',password:'',role:'RECEPCIONISTA'});await Swal.fire({icon:'success',title:'Usuario creado',text:'Deberá cambiar su contraseña al entrar.'});await load()}catch(e){await fail(e)}finally{busy.value=false}}
/** Confirma y aplica activación o baja administrativa. */
async function state(user:Usuario){if(!(await Swal.fire({title:`¿${user.activo?'Desactivar':'Activar'} a ${user.fullName}?`,icon:'question',showCancelButton:true,confirmButtonText:'Confirmar',cancelButtonText:'Cancelar'})).isConfirmed)return;try{await UsuarioFacade.state(user.id,!user.activo);await Swal.fire({icon:'success',title:'Estado actualizado'});await load()}catch(e){await fail(e)}}
/** Muestra temporal una vez y descarta su valor al cerrar. */
async function reset(user:Usuario){if(!(await Swal.fire({title:'¿Restablecer contraseña?',text:user.fullName,icon:'warning',showCancelButton:true,confirmButtonText:'Restablecer',cancelButtonText:'Cancelar'})).isConfirmed)return;try{const result=await UsuarioFacade.reset(user.id);await Swal.fire({title:'Contraseña temporal',text:result.temporaryPassword,footer:'Cópiala ahora. No podrás consultarla otra vez.',confirmButtonText:'Ya la guardé'});result.temporaryPassword='';await load()}catch(e){await fail(e)}}
onMounted(load)
</script>
<template><div class="stack"><header class="page-heading"><div><span class="eyebrow">Administración</span><h1>Usuarios y roles</h1></div><button class="primary" @click="open">Dar de alta usuario</button></header><section class="card table-card"><p v-if="loading" role="status">Cargando usuarios…</p><p v-else-if="error" role="alert">{{error}} <button @click="load">Reintentar</button></p><div v-else class="table-scroll"><table><thead><tr><th>Nombre</th><th>Correo</th><th>Rol</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><tr v-for="user in rows" :key="user.id"><td><span class="mini-avatar">{{user.fullName[0]}}</span>{{user.fullName}}</td><td class="mono">{{user.email}}</td><td><span class="chip">{{labels[user.role]}}</span></td><td>{{user.activo?'Activo':'Inactivo'}}</td><td><div class="actions"><button class="text-button" @click="state(user)">{{user.activo?'Desactivar':'Activar'}}</button><button class="text-button" @click="reset(user)">Restablecer contraseña</button></div></td></tr></tbody></table><p v-if="!rows.length">Aún no hay usuarios.</p></div><footer class="pagination"><span>{{total}} usuarios</span><div class="actions"><button :disabled="page===0" @click="page--;load()">Anterior</button><button :disabled="page+1>=pages" @click="page++;load()">Siguiente</button></div></footer></section><div v-if="panel" class="overlay drawer-overlay" @click.self="panel=false" @keydown.esc="panel=false"><section class="drawer" role="dialog" aria-modal="true" aria-labelledby="new-user"><button class="close" @click="panel=false">Cerrar ×</button><h2 id="new-user">Dar de alta usuario</h2><form class="stack" @submit.prevent="create"><label>Nombre completo<input v-model.trim="form.fullName" required minlength="2" maxlength="120"/></label><label>Correo<input v-model.trim="form.email" type="email" required maxlength="254"/></label><label>Contraseña temporal<input v-model="form.password" type="password" required minlength="12" maxlength="72" pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{12,72}"/><small>La persona deberá cambiarla en su primer acceso</small><small>12 caracteres, mayúscula, minúscula, número y símbolo.</small></label><label>Rol<select v-model="form.role"><option v-for="role in roles" :value="role.name" :key="role.name">{{labels[role.name]}}</option></select><small>{{roles.find(r=>r.name===form.role)?.description}}</small></label><div class="notice">Permisos del rol – Próximamente</div><div class="actions"><button type="button" class="secondary" @click="panel=false">Cancelar</button><button class="primary" :disabled="busy">{{busy?'Creando…':'Crear usuario'}}</button></div></form></section></div></div></template>
